package resource.bean.report;

// Generated 2012-8-14 9:48:50 by Hibernate Tools 3.4.0.CR1

/**
 * BiImportFieldConfig generated by hbm2java
 */
public class BiImportFieldConfig implements java.io.Serializable {

	private String id;
	private String importFileId;
	private String fieldName;
	private String fieldDesc;
	private String uniqueFlag;
	private Integer batchNo;
	private String fieldType;
	private String columnNum;
	private String defaultVal;
	private String fieldUpdateFlag;
	private String fieldUpdateType;
	private String mapFunction;
	private String mapParams;
	private String filterFlag;
	private String filterFunction;
	private String filterParams;
	private Integer nodeSeq;
	private String nodePath;
	private String nodeType;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getImportFileId() {
		return this.importFileId;
	}

	public void setImportFileId(String importFileId) {
		this.importFileId = importFileId;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldDesc() {
		return this.fieldDesc;
	}

	public void setFieldDesc(String fieldDesc) {
		this.fieldDesc = fieldDesc;
	}

	public String getUniqueFlag() {
		return uniqueFlag;
	}

	public void setUniqueFlag(String uniqueFlag) {
		this.uniqueFlag = uniqueFlag;
	}

	public Integer getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(Integer batchNo) {
		this.batchNo = batchNo;
	}

	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	public String getColumnNum() {
		return this.columnNum;
	}

	public void setColumnNum(String columnNum) {
		this.columnNum = columnNum;
	}

	public String getDefaultVal() {
		return this.defaultVal;
	}

	public void setDefaultVal(String defaultVal) {
		this.defaultVal = defaultVal;
	}

	public String getFieldUpdateType() {
		return this.fieldUpdateType;
	}

	public void setFieldUpdateType(String fieldUpdateType) {
		this.fieldUpdateType = fieldUpdateType;
	}

	public String getMapFunction() {
		return this.mapFunction;
	}

	public void setMapFunction(String mapFunction) {
		this.mapFunction = mapFunction;
	}

	public String getMapParams() {
		return this.mapParams;
	}

	public void setMapParams(String mapParams) {
		this.mapParams = mapParams;
	}

	public String getFilterFlag() {
		return this.filterFlag;
	}

	public void setFilterFlag(String filterFlag) {
		this.filterFlag = filterFlag;
	}

	public String getFilterFunction() {
		return this.filterFunction;
	}

	public void setFilterFunction(String filterFunction) {
		this.filterFunction = filterFunction;
	}

	public String getFilterParams() {
		return this.filterParams;
	}

	public void setFilterParams(String filterParams) {
		this.filterParams = filterParams;
	}

	public Integer getNodeSeq() {
		return this.nodeSeq;
	}

	public void setNodeSeq(Integer nodeSeq) {
		this.nodeSeq = nodeSeq;
	}

	public String getNodePath() {
		return this.nodePath;
	}

	public void setNodePath(String nodePath) {
		this.nodePath = nodePath;
	}

	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	public String getFieldUpdateFlag() {
		return fieldUpdateFlag;
	}

	public void setFieldUpdateFlag(String fieldUpdateFlag) {
		this.fieldUpdateFlag = fieldUpdateFlag;
	}

}
