package resource.bean.report;

// Generated 2012-8-20 15:52:38 by Hibernate Tools 3.4.0.CR1

/**
 * BiImportMapConfig generated by hbm2java
 */
public class BiImportMapConfig implements java.io.Serializable {

    private String id;
    private String mapType;
    private String typeFlag;
    private String inputValue;
    private String outValue;

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMapType() {
        return this.mapType;
    }

    public void setMapType(String mapType) {
        this.mapType = mapType;
    }

    public String getTypeFlag() {
        return this.typeFlag;
    }

    public void setTypeFlag(String typeFlag) {
        this.typeFlag = typeFlag;
    }

    public String getInputValue() {
        return this.inputValue;
    }

    public void setInputValue(String inputValue) {
        this.inputValue = inputValue;
    }

    public String getOutValue() {
        return this.outValue;
    }

    public void setOutValue(String outValue) {
        this.outValue = outValue;
    }

}
