package resource.bean.report;

// Generated 2012-8-20 15:52:38 by Hibernate Tools 3.4.0.CR1


/**
 * BiImportXmlConfig generated by hbm2java
 */
public class BiImportXmlConfig implements java.io.Serializable {

    private String id;
    private String pid;
    private String guid;
    private String nodeName;
    private String pnodeName;
    private Integer nodeOrder;
    private String nodeXpath;
    private String nodeProperty;
    private String nodeGetval;
    private String nodeRtval;

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPid() {
        return this.pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getNodeName() {
        return this.nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getPnodeName() {
        return this.pnodeName;
    }

    public void setPnodeName(String pnodeName) {
        this.pnodeName = pnodeName;
    }

    public Integer getNodeOrder() {
        return this.nodeOrder;
    }

    public void setNodeOrder(Integer nodeOrder) {
        this.nodeOrder = nodeOrder;
    }

    public String getNodeXpath() {
        return this.nodeXpath;
    }

    public void setNodeXpath(String nodeXpath) {
        this.nodeXpath = nodeXpath;
    }

    public String getNodeProperty() {
        return this.nodeProperty;
    }

    public void setNodeProperty(String nodeProperty) {
        this.nodeProperty = nodeProperty;
    }

    public String getNodeGetval() {
        return this.nodeGetval;
    }

    public void setNodeGetval(String nodeGetval) {
        this.nodeGetval = nodeGetval;
    }

    public String getNodeRtval() {
        return this.nodeRtval;
    }

    public void setNodeRtval(String nodeRtval) {
        this.nodeRtval = nodeRtval;
    }

}
